import re

inputFile = 'file.csv'
outputFile = 'file_done.csv'

# open file

f = open(inputFile,'r')
newData = f.read()
f.close()

# use SBL bible book abbreviation
newData = re.sub('【1】', r'Gen', newData, flags=re.M)
newData = re.sub('【2】', r'Exod', newData, flags=re.M)
newData = re.sub('【3】', r'Lev', newData, flags=re.M)
newData = re.sub('【4】', r'Num', newData, flags=re.M)
newData = re.sub('【5】', r'Deut', newData, flags=re.M)
newData = re.sub('【6】', r'Josh', newData, flags=re.M)
newData = re.sub('【7】', r'Judg', newData, flags=re.M)
newData = re.sub('【8】', r'Ruth', newData, flags=re.M)
newData = re.sub('【9】', r'1Sam', newData, flags=re.M)
newData = re.sub('【10】', r'2Sam', newData, flags=re.M)
newData = re.sub('【11】', r'1Kgs', newData, flags=re.M)
newData = re.sub('【12】', r'2Kgs', newData, flags=re.M)
newData = re.sub('【13】', r'1Chr', newData, flags=re.M)
newData = re.sub('【14】', r'2Chr', newData, flags=re.M)
newData = re.sub('【15】', r'Ezra', newData, flags=re.M)
newData = re.sub('【16】', r'Neh', newData, flags=re.M)
newData = re.sub('【17】', r'Esth', newData, flags=re.M)
newData = re.sub('【18】', r'Job', newData, flags=re.M)
newData = re.sub('【19】', r'Ps', newData, flags=re.M)
newData = re.sub('【20】', r'Prov', newData, flags=re.M)
newData = re.sub('【21】', r'Eccl', newData, flags=re.M)
newData = re.sub('【22】', r'Song', newData, flags=re.M)
newData = re.sub('【23】', r'Isa', newData, flags=re.M)
newData = re.sub('【24】', r'Jer', newData, flags=re.M)
newData = re.sub('【25】', r'Lam', newData, flags=re.M)
newData = re.sub('【26】', r'Ezek', newData, flags=re.M)
newData = re.sub('【27】', r'Dan', newData, flags=re.M)
newData = re.sub('【28】', r'Hos', newData, flags=re.M)
newData = re.sub('【29】', r'Joel', newData, flags=re.M)
newData = re.sub('【30】', r'Amos', newData, flags=re.M)
newData = re.sub('【31】', r'Obad', newData, flags=re.M)
newData = re.sub('【32】', r'Jonah', newData, flags=re.M)
newData = re.sub('【33】', r'Mic', newData, flags=re.M)
newData = re.sub('【34】', r'Nah', newData, flags=re.M)
newData = re.sub('【35】', r'Hab', newData, flags=re.M)
newData = re.sub('【36】', r'Zeph', newData, flags=re.M)
newData = re.sub('【37】', r'Hag', newData, flags=re.M)
newData = re.sub('【38】', r'Zech', newData, flags=re.M)
newData = re.sub('【39】', r'Mal', newData, flags=re.M)
newData = re.sub('【40】', r'Matt', newData, flags=re.M)
newData = re.sub('【41】', r'Mark', newData, flags=re.M)
newData = re.sub('【42】', r'Luke', newData, flags=re.M)
newData = re.sub('【43】', r'John', newData, flags=re.M)
newData = re.sub('【44】', r'Acts', newData, flags=re.M)
newData = re.sub('【45】', r'Rom', newData, flags=re.M)
newData = re.sub('【46】', r'1Cor', newData, flags=re.M)
newData = re.sub('【47】', r'2Cor', newData, flags=re.M)
newData = re.sub('【48】', r'Gal', newData, flags=re.M)
newData = re.sub('【49】', r'Eph', newData, flags=re.M)
newData = re.sub('【50】', r'Phil', newData, flags=re.M)
newData = re.sub('【51】', r'Col', newData, flags=re.M)
newData = re.sub('【52】', r'1Thess', newData, flags=re.M)
newData = re.sub('【53】', r'2Thess', newData, flags=re.M)
newData = re.sub('【54】', r'1Tim', newData, flags=re.M)
newData = re.sub('【55】', r'2Tim', newData, flags=re.M)
newData = re.sub('【56】', r'Titus', newData, flags=re.M)
newData = re.sub('【57】', r'Phlm', newData, flags=re.M)
newData = re.sub('【58】', r'Heb', newData, flags=re.M)
newData = re.sub('【59】', r'Jas', newData, flags=re.M)
newData = re.sub('【60】', r'1Pet', newData, flags=re.M)
newData = re.sub('【61】', r'2Pet', newData, flags=re.M)
newData = re.sub('【62】', r'1John', newData, flags=re.M)
newData = re.sub('【63】', r'2John', newData, flags=re.M)
newData = re.sub('【64】', r'3John', newData, flags=re.M)
newData = re.sub('【65】', r'Jude', newData, flags=re.M)
newData = re.sub('【66】', r'Rev', newData, flags=re.M)
newData = re.sub('【67】', r'Tob', newData, flags=re.M)
newData = re.sub('【70】', r'Wisdom', newData, flags=re.M)

# close file

f = open(outputFile,'w')
f.write(newData)
f.close()

